fix: Git Actions CI/CD 통합 (DURI-311)

diff --git a/.github/workflows/duri_ci_cd.yml b/.github/workflows/duri_ci_cd.yml
--- a/.github/workflows/duri_ci_cd.yml
+++ b/.github/workflows/duri_ci_cd.yml
@@ -1,11 +1,16 @@
-name: Duri-Be Server CI
+name: Duri Server CI/CD
 
 # PR 생성 트리거
 on:
   pull_request:
     branches: [ "develop" ]
 
-# BUILD 작업
+permissions:
+  contents: read
+
+env:
+  S3_BUCKET_NAME: duri-cicd-bucket
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -43,6 +48,22 @@ jobs:
       # 6. 빌드
       - name: Build with Gradle
         run: ./gradlew build
-      # 7. 압축
+      # 7. 압축 
       - name: Make zip file
         run: zip -r duri-git-build.zip ./build/libs/
+      # 8. AWS 연결
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.DURI_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.DURI_SECRET_ACCESS_KEY }}
+          aws-region: ap-northeast-2
+      # 9. S3 전송
+      - name: Upload to S3
+        run: |
+          if [ ! -f ./duri-git-build.zip ]; then
+            echo "Build file not found!"
+            exit 1
+          fi
+          aws s3 cp ./duri-git-build.zip s3://$S3_BUCKET_NAME/duri-aws-build.zip
+      # 10. EC2 배포
